version: "3.7"

services:
  db:
    image: postgres:16-alpine
    container_name: pgs_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5616pgsbot!server_2025
      POSTGRES_DB: pgs_bd
    ports:
      - "5432:5432"
    volumes:
      - postgres_pgs_data:/var/lib/postgresql/data

  # Spring Boot приложение
  app:
    build: .
    container_name: pgs-app
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pgs_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 5616pgsbot!server_2025
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    depends_on:
      - db
    networks:
      - bankcards-net
volumes:
  postgres_pgs_data: