version: "3.7"

services:
  db:
    image: postgres:16-alpine
    container_name: postgres_pgs_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pgs
    ports:
      - "5433:5432"
    volumes:
      - postgres_pgs_data:/var/lib/postgresql/data
volumes:
  postgres_pgs_data: