spring.application.name=pgs-backend


spring.datasource.url=jdbc:postgresql://localhost:5433/pgs_database
spring.datasource.username=postgres
spring.datasource.password=5616pgsbot!server_2025

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false


spring.liquibase.change-log=classpath:db/changelog/db.master.yaml
spring.liquibase.enabled=true