spring.application.name=pgs-backend


spring.datasource.url=jdbc:postgresql://localhost:5433/pgs
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:/db/changelog/db.master.yaml
spring.liquibase.enabled=true